name: pixelfield
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_bloc: ^9.1.0 # For state management
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7 # For state comparisons
  connectivity_plus: ^6.1.3 # To detect online/offline connectivity
  hive_flutter: ^1.1.0 # For local storage


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
     - family: EB Garamond
       fonts:
         - asset: assets/fonts/EBGaramond-Regular.ttf
           weight: 400
         - asset: assets/fonts/EBGaramond-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/EBGaramond-Bold.ttf
           weight: 700
         - asset: assets/fonts/EBGaramond-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/EBGaramond-Medium.ttf
           weight: 400
     - family: Lato
       fonts:
         - asset: assets/fonts/Lato-Regular.ttf
           weight: 400
         - asset: assets/fonts/Lato-Bold.ttf
           weight: 700
         - asset: assets/fonts/Lato-Light.ttf
           weight: 300
         - asset: assets/fonts/Lato-Black.ttf
           weight: 900
         - asset: assets/fonts/Lato-Thin.ttf
           weight: 100
